#Requires -Version 5.1
<#
.SYNOPSIS
    Install PersonalKnowledgeBase skills for your AI coding assistant (Windows).

.DESCRIPTION
    Creates symlinks (or copies as fallback) from your platform's skill
    directory to this repo's skills/ folder. Supports global (default) and
    local scopes — see examples.

.PARAMETER RemainingArguments
    Platform names (cursor, claude, copilot) and optional trailing scope:
    global (default) or local.

.PARAMETER Uninstall
    Remove skill symlinks/copies instead of installing.

.EXAMPLE
    .\setup.ps1 cursor
    .\setup.ps1 cursor global
    .\setup.ps1 cursor, claude global
    .\setup.ps1 cursor local
    .\setup.ps1 -Uninstall cursor
#>
param(
    [switch]$Uninstall,

    [Parameter(ValueFromRemainingArguments = $true)]
    [string[]]$RemainingArguments = @()
)

$ErrorActionPreference = "Stop"
$VERSION = "1.1.0"
$RepoDir = Split-Path -Parent $MyInvocation.MyCommand.Definition
$Skills = @("compile-wiki", "ask-wiki", "lint-wiki")

function Show-Usage {
    @"
Usage: .\setup.ps1 <platform>... [global|local]
       .\setup.ps1 -Uninstall <platform>...

Platforms: cursor, claude, copilot

Scopes (optional; default: global):
  global    Symlink skills, write global wiki-config next to skills,
            create raw/ and output/ in this repo.
  local     Symlink skills, scaffold a wiki in the current directory.

Examples:
  .\setup.ps1 cursor
  .\setup.ps1 cursor global
  .\setup.ps1 cursor, claude global
  .\setup.ps1 cursor local
  .\setup.ps1 -Uninstall cursor
"@ | Write-Host
    exit 1
}

function Resolve-TargetDir([string]$p) {
    switch ($p) {
        "cursor"  { return Join-Path $env:USERPROFILE ".cursor\skills" }
        "claude"  { return Join-Path $env:USERPROFILE ".claude\skills" }
        "copilot" { return Join-Path $env:USERPROFILE ".copilot\skills" }
    }
}

function Test-SymlinkSupport {
    $testDir = Join-Path $env:TEMP "pkb_symlink_test_$(Get-Random)"
    $testTarget = Join-Path $env:TEMP "pkb_symlink_target_$(Get-Random)"
    try {
        New-Item -ItemType Directory -Path $testTarget -Force | Out-Null
        New-Item -ItemType SymbolicLink -Path $testDir -Target $testTarget -ErrorAction Stop | Out-Null
        return $true
    }
    catch { return $false }
    finally {
        Remove-Item $testDir -Force -ErrorAction SilentlyContinue
        Remove-Item $testTarget -Recurse -Force -ErrorAction SilentlyContinue
    }
}

# Symlink or copy skills only (no wiki-config).
function Install-PlatformSkills([string]$p) {
    $targetDir = Resolve-TargetDir $p
    Write-Host "[$p] Installing skills (v$VERSION) to $targetDir"

    if (-not (Test-Path $targetDir)) {
        New-Item -ItemType Directory -Path $targetDir -Force | Out-Null
    }

    foreach ($skill in $Skills) {
        $src = Join-Path $RepoDir "skills\$skill"
        $dst = Join-Path $targetDir $skill

        if (Test-Path $dst) {
            $item = Get-Item $dst -Force
            if ($item.Attributes -band [IO.FileAttributes]::ReparsePoint) {
                $existing = $item.Target
                if ($existing -eq $src) {
                    Write-Host "  $skill -> already linked (skipped)"
                    continue
                }
                Write-Host "  $skill -> updating link (was: $existing)"
                Remove-Item $dst -Force
            }
            else {
                Write-Host "  $skill -> WARNING: directory exists and is NOT a symlink."
                Write-Host "           Back it up manually if needed, then re-run."
                continue
            }
        }

        if ($script:CanSymlink) {
            New-Item -ItemType SymbolicLink -Path $dst -Target $src | Out-Null
            Write-Host "  $skill -> linked"
        }
        else {
            Copy-Item -Path $src -Destination $dst -Recurse
            Write-Host "  $skill -> copied (symlinks unavailable, see note below)"
        }
    }
    Write-Host "[$p] Skills done.`n"
}

function Write-GlobalWikiConfig([string]$p) {
    $targetDir = Resolve-TargetDir $p
    $dateStr = Get-Date -Format "yyyy-MM-dd"
    $configContent = @"
# Wiki Configuration
> Generated by setup.ps1 on $dateStr. Do not edit manually.

- **Wiki root:** ``$RepoDir``
- **Wiki folder:** ``$RepoDir\wiki``
- **Raw folder:** ``$RepoDir\raw``
- **Output folder:** ``$RepoDir\output``
"@
    Set-Content -Path (Join-Path $targetDir "wiki-config.md") -Value $configContent
    Write-Host "[$p] wiki-config.md -> written (global)`n"
}

function Init-LocalWiki {
    $localRoot = (Get-Location).Path
    Write-Host "[local] Scaffolding wiki in: $localRoot"

    foreach ($dir in @("raw", "output", "wiki")) {
        $path = Join-Path $localRoot $dir
        if (-not (Test-Path $path)) {
            New-Item -ItemType Directory -Path $path -Force | Out-Null
        }
    }

    $indexPath = Join-Path $localRoot "wiki\index.md"
    if (-not (Test-Path $indexPath)) {
        $srcIndex = Join-Path $RepoDir "wiki\index.md"
        if (Test-Path $srcIndex) {
            Copy-Item $srcIndex $indexPath
        }
        else {
            @"
# Knowledge Base Index

Welcome to your compounding knowledge base! This file serves as the master taxonomy of all topics extracted from your raw files.

## Topics

<!-- Topics will appear here as you process raw files with compile-wiki.
     Each entry follows the format: "- Topic Name: One-line description" -->

---

*Note: Topics are extracted to prioritize general concepts, abstract ideas, processes, and subject matters rather than specific authors or individuals.*
"@ | Set-Content -Path $indexPath
        }
        Write-Host "  wiki/index.md -> created"
    }
    else {
        Write-Host "  wiki/index.md -> already exists (skipped)"
    }

    $logPath = Join-Path $localRoot "wiki\log.md"
    if (-not (Test-Path $logPath)) {
        $srcLog = Join-Path $RepoDir "wiki\log.md"
        if (Test-Path $srcLog) {
            Copy-Item $srcLog $logPath
        }
        else {
            @"
# Knowledge Base Processing Log

This log tracks which files from the ``raw/`` folder have been processed and when they were added to the wiki. It prevents the agent from needlessly re-processing old files.

| Date/Time | File Processed | Key Topics Extracted | Status |
|-----------|----------------|----------------------|--------|
"@ | Set-Content -Path $logPath
        }
        Write-Host "  wiki/log.md -> created"
    }
    else {
        Write-Host "  wiki/log.md -> already exists (skipped)"
    }

    $agentsPath = Join-Path $localRoot "AGENTS.md"
    if (-not (Test-Path $agentsPath)) {
        Copy-Item (Join-Path $RepoDir "AGENTS.md") $agentsPath
        Write-Host "  AGENTS.md -> copied from template"
    }
    else {
        Write-Host "  AGENTS.md -> already exists (skipped)"
    }

    $lintSrc = Join-Path $RepoDir "lint_graph.js"
    $lintDst = Join-Path $localRoot "lint_graph.js"
    if (-not (Test-Path $lintDst) -and (Test-Path $lintSrc)) {
        Copy-Item $lintSrc $lintDst
        Write-Host "  lint_graph.js -> copied from template (for /lint-wiki)"
    }
    elseif (Test-Path $lintDst) {
        Write-Host "  lint_graph.js -> already exists (skipped)"
    }

    $obsSrc = Join-Path $RepoDir "wiki\.obsidian"
    $obsDst = Join-Path $localRoot "wiki\.obsidian"
    if (-not (Test-Path $obsDst) -and (Test-Path $obsSrc)) {
        Copy-Item -Path $obsSrc -Destination $obsDst -Recurse
        Write-Host "  wiki/.obsidian/ -> copied from template"
    }
    elseif (Test-Path $obsDst) {
        Write-Host "  wiki/.obsidian/ -> already exists (skipped)"
    }
    else {
        Write-Host "  wiki/.obsidian/ -> template missing (skipped)"
    }

    $dateStr = Get-Date -Format "yyyy-MM-dd"
    $configContent = @"
# Wiki Configuration
> Generated by setup.ps1 (local) on $dateStr. Do not edit manually.

- **Wiki root:** ``$localRoot``
- **Wiki folder:** ``$localRoot\wiki``
- **Raw folder:** ``$localRoot\raw``
- **Output folder:** ``$localRoot\output``
"@
    Set-Content -Path (Join-Path $localRoot "wiki-config.md") -Value $configContent
    Write-Host "  wiki-config.md -> written (project root)"
    Write-Host "[local] Done.`n"
}

function Uninstall-Platform([string]$p) {
    $targetDir = Resolve-TargetDir $p
    Write-Host "[$p] Removing skills from $targetDir"

    foreach ($skill in $Skills) {
        $dst = Join-Path $targetDir $skill
        if (Test-Path $dst) {
            $item = Get-Item $dst -Force
            if ($item.Attributes -band [IO.FileAttributes]::ReparsePoint) {
                Remove-Item $dst -Force
                Write-Host "  $skill -> removed (symlink)"
            }
            else {
                Remove-Item $dst -Recurse -Force
                Write-Host "  $skill -> removed (copy)"
            }
        }
        else {
            Write-Host "  $skill -> not found (skipped)"
        }
    }
    $configFile = Join-Path $targetDir "wiki-config.md"
    if (Test-Path $configFile) {
        Remove-Item $configFile -Force
        Write-Host "  wiki-config.md -> removed"
    }
    Write-Host "[$p] Uninstalled.`n"
}

# --- Parse RemainingArguments ---

if ($null -eq $RemainingArguments -or $RemainingArguments.Count -eq 0) {
    Show-Usage
}

$validPlatforms = @("cursor", "claude", "copilot")
$platforms = [System.Collections.Generic.List[string]]::new()
$scope = "global"
$scopeCount = 0

foreach ($token in $RemainingArguments) {
    foreach ($part in ($token -split "," | ForEach-Object { $_.Trim() } | Where-Object { $_ })) {
        switch ($part) {
            "global" { $scope = "global"; $scopeCount++ }
            "local"  { $scope = "local"; $scopeCount++ }
            default {
                if ($validPlatforms -notcontains $part) {
                    Write-Host "Unknown argument: $part" -ForegroundColor Red
                    Show-Usage
                }
                $platforms.Add($part)
            }
        }
    }
}

if ($platforms.Count -eq 0) {
    Show-Usage
}

if ($scopeCount -gt 1) {
    Write-Host "Error: specify only one of 'global' or 'local'." -ForegroundColor Red
    exit 1
}

# --- Main ---

if ($Uninstall) {
    foreach ($p in $platforms) { Uninstall-Platform $p }
    exit 0
}

$script:CanSymlink = Test-SymlinkSupport

if (-not $script:CanSymlink) {
    Write-Host @"
NOTE: Symlinks are not available. Skills will be copied instead.
      To enable symlinks, turn on Developer Mode:
        Settings > System > For developers > Developer Mode
      Then re-run this script.
      With symlinks, git pull automatically updates your skills.
      With copies, re-run this script after pulling updates.

"@
}

if ($scope -eq "global") {
    try {
        $originUrl = & git -C $RepoDir remote get-url origin 2>$null
        if ($originUrl -and $originUrl -match "PersonalKnowledgeBaseCreator") {
            Write-Host "Disconnecting from template repository to prevent accidental pushes..."
            & git -C $RepoDir remote rename origin template-origin
            Write-Host "  origin -> renamed to 'template-origin'"
            Write-Host "  To push your wiki to your own repo, run:"
            Write-Host "    git remote add origin <your-repo-url>"
            Write-Host ""
        }
    } catch {}

    foreach ($dir in @("raw", "output")) {
        $path = Join-Path $RepoDir $dir
        if (-not (Test-Path $path)) {
            New-Item -ItemType Directory -Path $path -Force | Out-Null
        }
    }
}

foreach ($p in $platforms) {
    Install-PlatformSkills $p
    if ($scope -eq "global") {
        Write-GlobalWikiConfig $p
    }
}

if ($scope -eq "local") {
    Init-LocalWiki
}

Write-Host "Setup complete."
Write-Host ""
Write-Host "Quick start:"
if ($scope -eq "global") {
    Write-Host "  1. Edit AGENTS.md and fill in your focus areas"
    Write-Host "  2. Drop files into raw/"
    Write-Host '  3. Open in your AI assistant and say: "Compile the wiki"'
    Write-Host "  4. Browse wiki/ in Obsidian"
}
else {
    Write-Host "  1. Edit AGENTS.md in this directory and fill in your focus areas"
    Write-Host "  2. Drop files into raw/"
    Write-Host '  3. Open in your AI assistant and say: "Compile the wiki"'
    Write-Host "  4. Browse wiki/ in Obsidian"
}
