#!/usr/bin/env bash
set -euo pipefail

VERSION="1.1.2"
REPO_DIR="$(cd "$(dirname "$0")" && pwd)"
SKILLS=("compile-wiki" "ask-wiki" "lint-wiki")

usage() {
    cat <<EOF
Usage: $(basename "$0") <platform>... [global|local]
       $(basename "$0") --uninstall <platform>...

Install PersonalKnowledgeBase skills for your AI coding assistant.

Platforms:
  cursor    → ~/.cursor/skills/
  claude    → ~/.claude/skills/
  copilot   → ~/.copilot/skills/

Scopes (optional; default: global):
  global    Symlink skills, write global wiki-config next to skills,
            create raw/ and output/ in this repo (your cross-project wiki).
  local     Symlink skills, scaffold a wiki in the current directory
            (raw/, output/, wiki/, AGENTS.md, wiki-config.md). Overrides
            global when that file exists in the project root.

Examples:
  ./setup.sh cursor                    # same as: cursor global
  ./setup.sh cursor global
  ./setup.sh cursor claude global
  ./setup.sh cursor local              # init wiki in \$PWD (any project)

To uninstall:
  ./setup.sh --uninstall cursor
EOF
    exit 1
}

resolve_target_dir() {
    case "$1" in
        cursor)  echo "$HOME/.cursor/skills" ;;
        claude)  echo "$HOME/.claude/skills" ;;
        copilot) echo "$HOME/.copilot/skills" ;;
        *)
            echo "Unknown platform: $1" >&2
            echo "Supported: cursor, claude, copilot" >&2
            return 1
            ;;
    esac
}

# Symlink skills only (no wiki-config).
install_platform() {
    local platform="$1"
    local target_dir
    target_dir="$(resolve_target_dir "$platform")" || return 1

    echo "[$platform] Installing skills (v$VERSION) to $target_dir"
    mkdir -p "$target_dir"

    for skill in "${SKILLS[@]}"; do
        local src="$REPO_DIR/skills/$skill"
        local dst="$target_dir/$skill"

        if [ -L "$dst" ]; then
            local existing
            existing="$(readlink -f "$dst")"
            if [ "$existing" = "$src" ]; then
                echo "  $skill → already linked (skipped)"
                continue
            fi
            echo "  $skill → updating symlink (was: $existing)"
            rm "$dst"
        elif [ -d "$dst" ]; then
            echo "  $skill → WARNING: directory exists and is NOT a symlink."
            echo "           Back it up manually if needed, then re-run."
            continue
        fi

        ln -s "$src" "$dst"
        echo "  $skill → linked"
    done

    echo "[$platform] Skills done."
    echo ""
}

write_global_config() {
    local platform="$1"
    local target_dir
    target_dir="$(resolve_target_dir "$platform")" || return 1

    cat > "$target_dir/wiki-config.md" <<EOF
# Wiki Configuration
> Generated by setup.sh on $(date '+%Y-%m-%d'). Do not edit manually.

- **Wiki root:** \`$REPO_DIR\`
- **Wiki folder:** \`$REPO_DIR/wiki\`
- **Raw folder:** \`$REPO_DIR/raw\`
- **Output folder:** \`$REPO_DIR/output\`
EOF
    echo "[$platform] wiki-config.md → written (global)"
    echo ""
}

# Scaffold a project-local wiki in the current working directory.
init_local() {
    local local_root
    local_root="$(pwd)"

    echo "[local] Scaffolding wiki in: $local_root"

    mkdir -p "$local_root/raw" "$local_root/output" "$local_root/wiki"

    if [ ! -f "$local_root/wiki/index.md" ]; then
        if [ -f "$REPO_DIR/wiki/index.md" ]; then
            cp "$REPO_DIR/wiki/index.md" "$local_root/wiki/index.md"
        else
            cat > "$local_root/wiki/index.md" <<'IDX'
# Knowledge Base Index

Welcome to your compounding knowledge base! This file serves as the master taxonomy of all topics extracted from your raw files.

## Topics

<!-- Topics will appear here as you process raw files with compile-wiki.
     Each entry follows the format: "- Topic Name: One-line description" -->

---

*Note: Topics are extracted to prioritize general concepts, abstract ideas, processes, and subject matters rather than specific authors or individuals.*
IDX
        fi
        echo "  wiki/index.md → created"
    else
        echo "  wiki/index.md → already exists (skipped)"
    fi

    if [ ! -f "$local_root/wiki/log.md" ]; then
        if [ -f "$REPO_DIR/wiki/log.md" ]; then
            cp "$REPO_DIR/wiki/log.md" "$local_root/wiki/log.md"
        else
            cat > "$local_root/wiki/log.md" <<'LOG'
# Knowledge Base Processing Log

This log tracks which files from the `raw/` folder have been processed and when they were added to the wiki. It prevents the agent from needlessly re-processing old files.

| Date/Time | File Processed | Key Topics Extracted | Status |
|-----------|----------------|----------------------|--------|
LOG
        fi
        echo "  wiki/log.md → created"
    else
        echo "  wiki/log.md → already exists (skipped)"
    fi

    if [ ! -f "$local_root/AGENTS.md" ]; then
        cp "$REPO_DIR/AGENTS.md" "$local_root/AGENTS.md"
        echo "  AGENTS.md → copied from template"
    else
        echo "  AGENTS.md → already exists (skipped)"
    fi

    if [ ! -f "$local_root/lint_graph.js" ] && [ -f "$REPO_DIR/lint_graph.js" ]; then
        cp "$REPO_DIR/lint_graph.js" "$local_root/lint_graph.js"
        echo "  lint_graph.js → copied from template (for /lint-wiki)"
    elif [ -f "$local_root/lint_graph.js" ]; then
        echo "  lint_graph.js → already exists (skipped)"
    fi

    if [ ! -d "$local_root/wiki/.obsidian" ] && [ -d "$REPO_DIR/wiki/.obsidian" ]; then
        cp -R "$REPO_DIR/wiki/.obsidian" "$local_root/wiki/.obsidian"
        echo "  wiki/.obsidian/ → copied from template"
    elif [ -d "$local_root/wiki/.obsidian" ]; then
        echo "  wiki/.obsidian/ → already exists (skipped)"
    else
        echo "  wiki/.obsidian/ → template missing (skipped)"
    fi

    cat > "$local_root/wiki-config.md" <<EOF
# Wiki Configuration
> Generated by setup.sh (local) on $(date '+%Y-%m-%d'). Do not edit manually.

- **Wiki root:** \`$local_root\`
- **Wiki folder:** \`$local_root/wiki\`
- **Raw folder:** \`$local_root/raw\`
- **Output folder:** \`$local_root/output\`
EOF
    echo "  wiki-config.md → written (project root)"
    echo "[local] Done."
    echo ""
}

uninstall_platform() {
    local platform="$1"
    local target_dir
    target_dir="$(resolve_target_dir "$platform")" || return 1

    echo "[$platform] Removing skill symlinks from $target_dir"
    for skill in "${SKILLS[@]}"; do
        local dst="$target_dir/$skill"
        if [ -L "$dst" ]; then
            rm "$dst"
            echo "  $skill → removed"
        elif [ -e "$dst" ]; then
            echo "  $skill → skipped (not a symlink, won't touch it)"
        else
            echo "  $skill → not found (skipped)"
        fi
    done
    if [ -f "$target_dir/wiki-config.md" ]; then
        rm "$target_dir/wiki-config.md"
        echo "  wiki-config.md → removed"
    fi
    echo "[$platform] Uninstalled."
    echo ""
}

# --- Main ---

[ $# -eq 0 ] && usage

UNINSTALL=false
PLATFORMS=()
SCOPE=global
SCOPE_COUNT=0

for arg in "$@"; do
    case "$arg" in
        --uninstall) UNINSTALL=true ;;
        --help|-h)   usage ;;
        global)
            SCOPE=global
            SCOPE_COUNT=$((SCOPE_COUNT + 1))
            ;;
        local)
            SCOPE=local
            SCOPE_COUNT=$((SCOPE_COUNT + 1))
            ;;
        *)
            PLATFORMS+=("$arg")
            ;;
    esac
done

[ ${#PLATFORMS[@]} -eq 0 ] && usage

if [ "$SCOPE_COUNT" -gt 1 ]; then
    echo "Error: specify only one of 'global' or 'local'." >&2
    exit 1
fi

if $UNINSTALL; then
    for p in "${PLATFORMS[@]}"; do
        uninstall_platform "$p"
    done
    exit 0
fi

if [ "$SCOPE" = "global" ]; then
    # Disconnect from the template origin (repo only)
    if git -C "$REPO_DIR" remote get-url origin 2>/dev/null | grep -qi "PersonalKnowledgeBaseCreator"; then
        echo "Disconnecting from template repository to prevent accidental pushes..."
        git -C "$REPO_DIR" remote rename origin template-origin
        echo "  origin → renamed to 'template-origin'"
        echo "  To push your wiki to your own repo, run:"
        echo "    git remote add origin <your-repo-url>"
        echo ""
    fi

    mkdir -p "$REPO_DIR/raw" "$REPO_DIR/output"
fi

for p in "${PLATFORMS[@]}"; do
    install_platform "$p"
    if [ "$SCOPE" = "global" ]; then
        write_global_config "$p"
    fi
done

if [ "$SCOPE" = "local" ]; then
    init_local
fi

echo "Setup complete. Skills are symlinked — git pull updates them automatically."
echo ""
echo "Quick start:"
if [ "$SCOPE" = "global" ]; then
    echo "  1. Edit AGENTS.md and fill in your focus areas"
    echo "  2. Drop files into raw/"
    echo "  3. Open in your AI assistant and say: 'Compile the wiki'"
    echo "  4. Browse wiki/ in any editor (Obsidian optional — open wiki/ as a vault for graph view)"
else
    echo "  1. Edit AGENTS.md in this directory and fill in your focus areas"
    echo "  2. Drop files into raw/"
    echo "  3. Open in your AI assistant and say: 'Compile the wiki'"
    echo "  4. Browse wiki/ in any editor (Obsidian optional — open wiki/ as a vault for graph view)"
fi
